---
title: "Phoneme"
output: html_notebook
---

1. 被験者ごとのデータをまとめる
  * 産出課題: 無声化率(環境毎)
  * 近畿の居住年数
1. 被験者ごとのデータをまとめる
  * 無声化
    * AXB
    * 判定課題
  * トーンの復元
  
タスクの確認

item_id がないのは練習問題

* production
* axb
  * item_id でタスクが分かれる
* cat
  * item_id でタスクが分かれる
* rate(音としてどれくらい良いか)
  * item_id でタスクが分かれる

```{r}
library(dplyr)
library(ggplot2)
library(readr)
library(stringr)
library(tidyr)
```

```{r}
source("script/subject_info.R")
# TODO: devocingのデータをマージしたほうが早い。
subject_info_sone <- read_csv("csv/illusory-vowel-keihan.csv") %>%
  extract_columns(data_src = "sone")
subject_info_cw <- read_csv("csv/illusory-vowel-keihan-cw.csv") %>%
  extract_columns(data_src = "cw")
subject_info <- rbind(subject_info_sone, subject_info_cw)

results <- rbind(
  read_csv("csv/illusory-vowel-keihan.csv") %>% mutate(data_src = "sone"),
  read_csv("csv/illusory-vowel-keihan-cw.csv") %>% mutate(data_src = "cw")
) %>%
  filter(task == "axb") %>%
  left_join(subject_info, by = c("run_id", "data_src")) %>%
  select(c(run_id, item_id, is_correct, rt, span_kinki, span_tokyo, span_unknown, age, data_src, correct)) %>%
  mutate(item_id = as.numeric(item_id)) %>%
  mutate(rt = as.numeric(rt)) %>%
  mutate(item_id = as.numeric(item_id)) %>%
  mutate(is_correct = is_correct == "true") %>%
  drop_na()
head(results)
```

無声化

https://docs.google.com/document/d/1OKkkZ4sELLtTBjiBWUG_P37EsWdFsidrGv0eOqiwIic/edit?usp=sharing

```{r}
# 文脈などのカラムをひっぱるのも可能
# type==target が 無声化, filler がトーンの知覚
item_list <- read_csv("../src/list/axb_list.csv") %>% select(c(item_id, type, condition, correct, item_a, item_x, item_b))
axb_results_devoice <- merge(results, item_list, on = "item_id") %>% filter(type == "target")
```

a を違うと早とちりするとこうなる。

```{r}
axb_results_devoice %>%
  mutate(span_kinki = span_kinki > 5) %>%
  ggplot() +
  facet_grid(correct ~ span_kinki) +
  geom_histogram(aes(x = condition, color = is_correct, fill = is_correct), stat = "count", position = "fill")
```
