---
title: "Categorize"
output: github_document
---

- 概要: https://docs.google.com/document/d/1rk5MHMvD5-6SWT7H2nkc-r7v3KvH-dzt_OdftNrDe-I/edit?usp=sharing
- 作業説明: https://docs.google.com/document/d/1U3FCDh8NETS-9mWDLfTU_0mZx9jJpFgkisukI58nV64/edit?usp=sharing

行う分析チェックリスト

> 音がどの表記（ひらがな）に当てはまり(8候補)、
> choices: ['えすぽ', 'えずぼ', 'えくと', 'えぐど', 'えぷそ', 'えぶぞ', 'えつこ', 'えづご'],
> どの程度一致しているかを1--7段階で評価

- [ ] カテゴライズとしての良し悪し

```{r}
library(dplyr)
library(ggplot2)
library(readr)
library(stringr)
library(tidyr)
source("script/subject_info.R")
source("script/results_pitch.R") # load mutated data
```
```{r}
# 前の
# cat と rate がある。
read_csv("csv/illusory-vowel-keihan-cw.csv")
```

1. catのタスクを見る
  1. 想定されたものを選んでもらえたか
  1. 想定されたものとしての評価は低すぎないか
  1. sp とかがナチュラルかも気になる（近畿ではないので）

```{r}
# epuso-1.wavなどのaudio列を.で分割し、最初の要素を phoneme, speaker とする
item_list <- read_csv("../src/list/cat_list.csv") %>%
  rowwise() %>%
  mutate(
    wav_base = str_split(audio, "\\.")[[1]][1],
    phoneme = str_split(wav_base, "-")[[1]][1],
    speaker = str_split(wav_base, "-")[[1]][2]
  )

# 被験者情報
subject_info_sone <- read_csv("csv/illusory-vowel-keihan.csv") %>%
  extract_columns(data_src = "sone")
subject_info_cw <- read_csv("csv/illusory-vowel-keihan-cw.csv") %>%
  extract_columns(data_src = "cw")
subject_info <- rbind(subject_info_sone, subject_info_cw)

# cwデータと曽根さんデータのマージ
results_bound =  rbind(
read_csv("csv/illusory-vowel-keihan.csv") %>% mutate(data_src = "sone"),
read_csv("csv/illusory-vowel-keihan-cw.csv") %>% mutate(data_src = "cw")
)

# まずrate同数行を抜き出して横につける。
library(purrr)
results_rate <- results_bound %>% 
  filter(task == "rate") %>% mutate(rate = extract_numeric(response)) %>% 
  select(c(rate))
```


```{r}
choices[1]
results_bound
# results_bound %>% 
#   filter(task == "cat") %>%
#   mutate(selected_choice = choices[as.integer(response)])

selected_idx = results_bound %>%  filter(task == "cat") %>% select(response) %>% unlist %>% as.integer()
print(selected_idx)
# choices = c('えすぽ', 'えずぼ', 'えくと', 'えぐど', 'えぷそ', 'えぶぞ', 'えつこ', 'えづご')
choices = c('esupo', 'ezubo', 'ekuto', 'egudo', 'epuso', 'epuzo', 'etsuko', 'edzugo')
print(choices)
print(choices[selected_idx])
choices[0]
choices
choices
selected_idx
```


```{r}
# %>% 
  left_join(subject_info, by = c("run_id", "data_src")) %>%
  select(c(run_id, item_id, response, rate, span_kinki, span_tokyo, span_unknown, age, data_src, type)) %>%
  drop_na() %>%
  mutate(
    tokyo_kinki_ratio = (span_tokyo - span_kinki) / age
  ) %>%
  filter(age > 18) %>%
  merge(item_list, on = "item_id") %>%
  filter(type == "target") #  %>%

nrow(results_cat)

results_cat
```



```{r}
results %>% ggplot() +
  facet_grid(speaker ~ phoneme) +
  geom_histogram(aes(x = response), stat = "count")
```

```{r}
print("EOF")
```
