---
title: "Follow Up Survey"
output: github_document
---

1. 無理に前提を置く必要はない。
https://github.com/kishiyamat/illusory-vowel-keihan/pull/118 をベースに資料を作成

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(ggplot2)
library(readr)
library(stringr)
library(tidyr)
source("script/subject_info.R")
source("script/results_pitch.R") # load mutated data
```

単語とかはともかく、ピッチパターンが許容できるかを確認する

東京パターンか否かで考える

- 小豆(HHL-HLL-*LHH*)
- カラス(*HLL*--LHH--LLH)
- 言葉(HHL--HLL--*LHH*)
- ウサギ(*LHH*--LLH)

```{r}
results <- read_csv("follow-up.csv") %>%
  rename(
    input_id = "クラウドワークスのワーカー名",
    age = "現在の年齢"
  ) %>%
  pivot_longer(
    cols = contains("H"),
    names_to = "stimuli",
    values_to = "evaluation"
  ) %>%
  select(
    c(input_id, stimuli, evaluation)
  ) %>%
  mutate(
    word = gsub("[HL（）]", "", stimuli),
    word = case_when(
      word == "ウサギ" ~ "usagi",
      word == "カラス" ~ "karasu",
      word == "言葉" ~ "kotoba",
      word == "小豆" ~ "azuki",
      TRUE ~ "other"
    ),
    pattern = case_when(
      stimuli %in% c("小豆（LHH）", "カラス（HLL）", "言葉（LHH）", "ウサギ（LHH）") ~ "tokyo",
      TRUE ~ "other"
    ),
    eval_int = case_when(
      evaluation == "よく聞く" ~ 3,
      evaluation == "時々聞く" ~ 2,
      evaluation == "あまり聞いたことがない" ~ 1,
      evaluation == "全く聞いたことがない" ~ 0
    )
  ) %>%
  group_by(input_id, pattern, word) %>%
  # 最大値を取れば外れ値などは関係ない
  # 平均は非東京パターンで割れたとき（0と3など）1.5などになってしまう。
  summarise(eval_by_pattern = max(eval_int)) %>%
  ungroup()
results
```

```{r}
item_list <- read_csv("../src/list/axb_list.csv") %>%
  select(c(item_id, type, condition, correct, item_a, item_x, item_b, c1, c2))
subject_info_sone <- read_csv("csv/illusory-vowel-keihan.csv") %>%
  extract_columns(data_src = "sone")
subject_info_cw <- read_csv("csv/illusory-vowel-keihan-cw.csv") %>%
  extract_columns(data_src = "cw")
# ここの input_id で合わせればいい
subject_info <- rbind(subject_info_sone, subject_info_cw) %>%
  mutate(
    span_tokyo_span_kinki = span_tokyo - span_kinki,
    tokyo_kinki_ratio = (span_tokyo - span_kinki) / age
  )
```
```{r}
follow_list <- results$input_id %>% unique()
# ↑に存在するが↓に存在しないパターンがよろしくない。
original_list <- subject_info %>%
  filter(data_src == "cw") %>%
  select(input_id) %>%
  unlist() %>%
  unique()
# これらが問題
# 28しかない。4件落ちている。年齢から推定する(?)
`%notin%` <- Negate(`%in%`)
follow_list[follow_list %notin% original_list]
```


```{r}
# head(subject_info)
merged_results <- results %>% merge(subject_info)
head(merged_results)
```

```{r}
# -1から1の値を取る(まぁ0--4に分割、とかでいいか。)
g <- merged_results %>%
  ggplot() +
  facet_grid(pattern ~ word) +
  geom_violin(aes(
    x = factor(range01(tokyo_kinki_ratio), 4),
    y = eval_by_pattern,
    color = pattern,
    fill = pattern
  )) +
  theme_bw() +
  scale_shape_manual(values = c(16, 21)) +
  # scale_fill_manual(values = c("black", "white")) +
  theme(
    legend.position = "none",
    axis.title.y = element_blank()
  ) +
  theme(
    axis.text = element_text(size = 9),
    axis.title = element_text(size = 12, face = "bold"),
    strip.text.x = element_text(size = 9),
    axis.title.x = element_blank()
  )

ggsave(file = "artifact/follow_up.pdf", g, width = 8, height = 8, units = "cm")
ggsave(file = "artifact/follow_up.png", g, width = 8, height = 8, units = "cm")
```

東京居住歴が長くて東京以外のパターンを聞いたことがある人はいないが、
東京居住歴が短くて東京のパターンを聞いたことのある人はいる。

```{r}
library(lmerTest)
model <- lmer(
  eval_by_pattern ~
  pattern * tokyo_kinki_ratio + (1 | input_id) + (1 | word),
  data = merged_results
)
```

```{r}
summary(model)
```

```{r}
print("EOF")
```
